version: "3"
services:
#  contappserv:
#    build: .
#    image: imgapp
#    ports:
#      - "8080:8080"
#    container_name: contapp
#    networks:
#      - springnetwork

  testserv:
    build:
      dockerfile: in-memory-tests/Dockerfile
    image: testsimg
    container_name: testscont
    networks:
      - springnetwork


networks:
  springnetwork:
    driver: bridge
    
